# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_add_consumption_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='Consumption',
            new_name='consumption',
        ),
    ]
