# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_make_consumption_field_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='consumption.UserData'),
            preserve_default=False,
        ),
    ]
